spring:
  datasource:
    url: jdbc:mysql://172.17.0.1:3306/qbt?useSSL=false&serverTimezone=CTT&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: 123456
  redis:
    host: 172.17.0.1
    port: 6379
    database: 0
    password: 123456
jedis:
  password: 123456
  host: 172.17.0.1