mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  datasource:
    url: jdbc:mysql://47.101.151.125:3306/qu-bao-tang?useSSL=false&serverTimezone=CTT&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: 123456
  redis:
    host: 47.101.151.125
    port: 6379
    database: 0
    password: 123456
jedis:
  password: 123456