server:
  undertow:
    io-threads: 8
    worker-threads: 128
    buffer-size: 1024
    direct-buffers: true
mybatis:
  type-aliases-package: com.fanglin.entity,com.fanglin.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: com.fanglin.common.core.enums.CodeEnumTypeHandler
mapper:
  safe-delete: true
  safe-update: true
  enum-as-simple-type: true
spring:
  jmx:
    enabled: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://47.101.151.125:3306/qu-bao-tang?useSSL=false&serverTimezone=CTT&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: 123456
    hikari:
      minimum-idle: 1
      maximum-pool-size: 2000
      pool-name: hikariCP
      connection-timeout: 10000
common:
  #静态资源默认保存根路径
  static-dir: /data/static/qu_bao_tang/
jedis:
  password: 123456
  host: 47.101.151.125
gaode:
  key: 4a4775afef857b08ca7e3ed2407a91ba
push:
  app-key: 309b096fa91403d46616e9ca
  master-secret: 1888f0421cbcc93f63b330d3
sms:
  zhu-tong:
    account: sfsfhy
    password: jLkdrz
wx:
  app-id: wxd04cf729f344bdc3
  secret: 65520fb3cf19ad99aea4747c7a77c9f8
swagger:
  title: 趣宝堂
  description: 趣宝堂API文档
  version: 1.0.0